# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm

    mappings:
        subscription_logo: # <--- Vérifie ce nom précisément
            uri_prefix: /logos
            upload_destination: '%kernel.project_dir%/public/logos'
            namer: vich_uploader.namer_uniqid
